-- https://school.programmers.co.kr/learn/courses/30/lessons/131123
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM(
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
        ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS REST_NUM
    FROM REST_INFO
    ) AS RANKED_REST
WHERE REST_NUM = 1
ORDER BY FOOD_TYPE DESC;
