-- https://school.programmers.co.kr/learn/courses/30/lessons/131533 

SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT NATURAL JOIN OFFLINE_SALE
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
