-- https://school.programmers.co.kr/learn/courses/30/lessons/131118
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, round(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
NATURAL JOIN REST_REVIEW R
WHERE ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;
